version: "2"

run:
  relative-path-mode: gomod

linters:
  enable:
    - errcheck
    - gocyclo
    - gosec
    - ineffassign
    - prealloc
    - unused
    #! AutoFix
    - gocritic
    - govet
    - perfsprint
    - staticcheck
  settings:
    gocyclo:
      min-complexity: 15
    #! AutoFix
    gocritic:
      disabled-checks:
        - commentFormatting
    govet:
      enable:
        - shadow
    staticcheck:
      checks:
        - all
        - -QF1008
        #! Default
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
  exclusions:
    paths:
      - dist
      - ignore
      - node_modules
      - temp
      - tmp

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/bastean/codexgo/v4
  exclusions:
    paths:
      - dist
      - ignore
      - node_modules
      - temp
      - tmp
