version: "3"

vars:
  # ---------------------------------- Fluxbox --------------------------------- #

  FLUXBOX_MENU: ~/.fluxbox/menu

tasks:
  # ---------------------------------------------------------------------------- #
  #                                 Devcontainer                                 #
  # ---------------------------------------------------------------------------- #

  devcontainer-*/*:
    requires:
      vars: ["USER", "PASSWORD"]
    vars:
      USER: "{{index .MATCH 0}}"
      PASSWORD: "{{index .MATCH 1}}"
    cmds:
      - task: bash
        vars:
          RUN: echo -e "{{.PASSWORD}}\n{{.PASSWORD}}" | sudo passwd {{.USER}}
      - task: init

  connect-*/*@*:
    requires:
      vars: ["PORT", "USER", "HOST"]
    vars:
      PORT: "{{index .MATCH 0}}"
      USER: "{{index .MATCH 1}}"
      HOST: "{{index .MATCH 2}}"
    cmds:
      - ssh -p {{.PORT}} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null {{.USER}}@{{.HOST}}

  # ---------------------------------------------------------------------------- #
  #                                    Desktop                                   #
  # ---------------------------------------------------------------------------- #

  fluxbox-menu:
    internal: true
    requires:
      vars: ["OLD", "NEW"]
    cmds:
      - task: replace
        vars:
          OLD: \({{.OLD}}\)\s\{.*\}
          NEW: \({{.OLD}}\) \{ {{.NEW}} \}
          FILE: "{{.FLUXBOX_MENU}}"

  desktop:
    vars:
      MENU:
        ref: dict "File Manager" "xfe" "Terminal" "terminator" "Web Browser" "chromium"
    cmds:
      - sudo apt install -y xfe terminator chromium
      - for:
          var: MENU
        task: fluxbox-menu
        vars:
          OLD: "{{.KEY}}"
          NEW: "{{.ITEM}}"
