// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func InitListeners(PutAuthorization, DeleteAuthorization string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_InitListeners_0d34`,
		Function: `function __templ_InitListeners_0d34(PutAuthorization, DeleteAuthorization){document.addEventListener('alpine:init', () => {
        Alpine.store('codexgo', {
            codexgo_jwt: Alpine.$persist(""),
            getJWT () { return this.codexgo_jwt.initialValue },
            setJWT (token) { this.codexgo_jwt = Alpine.$persist(token) }
        })
    })

    document.addEventListener('htmx:configRequest', function(evt) {
        evt.detail.headers['Authorization'] = Alpine.store('codexgo').getJWT()
    });

    document.addEventListener(PutAuthorization, function(evt) {
        const token = evt.detail.value
        Alpine.store('codexgo').setJWT(token)
    });

    document.addEventListener(DeleteAuthorization, function(evt) {
        Alpine.store('codexgo').setJWT("")
    });
}`,
		Call:       templ.SafeScript(`__templ_InitListeners_0d34`, PutAuthorization, DeleteAuthorization),
		CallInline: templ.SafeScriptInline(`__templ_InitListeners_0d34`, PutAuthorization, DeleteAuthorization),
	}
}
